use_default_settings:
  engines:
    keep_only:
      - bing
      - duckduckgo
      - wikipedia
      - brave

general:
  instance_name: "Trinyx CE Search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "replace-with-SEARXNG_SECRET"
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"

ui:
  static_use_hash: true
