#!/usr/bin/env bash
set -euo pipefail

if grep -RniE \
  --include='*.java' --include='*.ts' --include='*.tsx' --include='*.js' \
  --include='*.mjs' --include='*.yml' --include='*.yaml' --include='*.sh' \
  --include='*.txt' --include='*.json' --include='*.md' \
  'Welcome to LiveContext|LiveContext Agent Tools|LiveContext API key|LiveContext Cloud account|via LiveContext Cloud|Auto-generated by LiveContext CE|^# LiveContext Community Edition|github[.]com/eddine[r]abii/Trinyx' \
  backend frontend cli \
  --exclude-dir=target --exclude-dir=node_modules --exclude-dir=test \
  --exclude-dir=tests --exclude-dir=__tests__ --exclude-dir=migration
then
  echo "User-facing LiveContext product identity remains in runtime source" >&2
  exit 1
fi

if git grep -nEI 'eddine[r]abii|eddine[.]rabii|ghcr[.]io/eddine[r]abii|github[.]com/eddine[r]abii/Trinyx|raw[.]githubusercontent[.]com/livecontext-ai/livecontext-ce/.*/liveContext[-]logo[.]png' -- .; then
  echo "A retired repository owner, image namespace or LiveContext logo remains in tracked source" >&2
  exit 1
fi

grep -Fq '"homepage": "https://github.com/TrinyxAI/Trinyx"' cli/package.json
grep -Fq 'github.com/TrinyxAI/Trinyx' frontend/public/llms.txt
grep -Fq 'github.com/TrinyxAI/Trinyx' README.md
grep -Fq 'raw.githubusercontent.com/TrinyxAI/Trinyx/main/frontend/public/branding/trinyx-logo.png' \
  templates/portainer/trinyx-ce.json
grep -Fq 'Trinyx Agent Tools' \
  backend/agent-common/src/main/java/com/apimarketplace/agent/mcp/McpMessageTypes.java
