name: Build Release Candidate

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: TrinyxAI/Trinyx/.github/workflows/build-release-candidate-impl.yml@114a2613e8090f034925a1bcf148f055653c3a06
