name: Build Release Candidate

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build-release-candidate-impl.yml
